# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 13, 54, 31, 381397, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 13, 55, 6, 890121, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
