# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170116_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
