# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170116_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='article_image'),
        ),
    ]
